# Generated by Django 6.0.4 on 2026-05-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(default='Critical Threat', max_length=255)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
